import { useEffect, useState } from 'react';
import { ArrowRight, CheckCircle2, Mail, MapPin, MessageCircle, Phone, Send } from 'lucide-react';
import { Link } from 'react-router';
import { whatsappUrl } from '../Shared/whatsapp';

const PageShell = ({ eyebrow, title, intro, children }) => (
  <div className="bg-surface-soft px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl"><p className="text-sm font-bold uppercase tracking-widest text-primary-600">{eyebrow}</p><h1 className="mt-2 text-4xl font-black text-text sm:text-5xl">{title}</h1>{intro && <p className="mt-4 max-w-2xl text-lg leading-relaxed text-text-muted">{intro}</p>}<div className="mt-10">{children}</div></div></div>
);

export const About = () => (
  <PageShell eyebrow="Our story" title="Play is how big ideas begin." intro="A to Z Kids World brings together thoughtful toys that help children wonder, build, make, and grow. Every discovery is chosen to make learning feel like an adventure.">
    <div className="grid gap-6 md:grid-cols-3"><div className="rounded-3xl bg-primary-100 p-6"><p className="text-4xl font-black text-primary-700">21+</p><p className="mt-2 font-bold text-text">Curated discoveries</p><p className="mt-2 text-sm text-text-muted">A growing collection for creative play.</p></div><div className="rounded-3xl bg-accent-100 p-6"><p className="text-4xl font-black text-accent-1100">100%</p><p className="mt-2 font-bold text-text">Curiosity approved</p><p className="mt-2 text-sm text-text-muted">Products selected for hands-on fun.</p></div><div className="rounded-3xl bg-secondary-100 p-6"><p className="text-4xl font-black text-secondary-1000">1</p><p className="mt-2 font-bold text-text">Happy mission</p><p className="mt-2 text-sm text-text-muted">Make every playtime count.</p></div></div><div className="mt-8 grid gap-8 rounded-3xl border border-border bg-surface p-6 sm:p-8 md:grid-cols-2"><div><h2 className="text-2xl font-black text-text">Made for growing minds</h2><p className="mt-3 leading-relaxed text-text-muted">From first puzzles to big STEM experiments, our collection is designed to invite children into the kind of play that builds confidence, imagination, and connection.</p></div><div className="space-y-4 text-sm font-semibold text-text"><div className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-primary-600" /> Age-conscious recommendations</div><div className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-primary-600" /> Friendly support through WhatsApp</div><div className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-primary-600" /> Local, simple ordering experience</div></div></div></PageShell>
);

export const Contact = () => {
  const [sent, setSent] = useState(false);
  useEffect(() => {
    document.querySelector('a[href="https://wa.me/15551234567"]')?.setAttribute('href', whatsappUrl);
  }, []);
  return <PageShell eyebrow="We are here to help" title="Let&apos;s talk about play." intro="Have a question about a product, delivery, or choosing the right discovery? Send us a note and our team will get back to you."><div className="grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><div className="rounded-3xl bg-secondary-900 p-6 text-white sm:p-8"><h2 className="text-2xl font-black">Contact details</h2><p className="mt-3 text-sm leading-relaxed text-secondary-100">Our friendly team is ready to help you find the right next adventure.</p><div className="mt-8 space-y-5 text-sm"><div className="flex gap-3"><MessageCircle className="h-5 w-5 shrink-0 text-accent-600" /><span>Chat with us on WhatsApp</span></div><div className="flex gap-3"><Mail className="h-5 w-5 shrink-0 text-accent-600" /><span>hello@atozkids.com</span></div><div className="flex gap-3"><Phone className="h-5 w-5 shrink-0 text-accent-600" /><span>+1 (555) 123-4567</span></div><div className="flex gap-3"><MapPin className="h-5 w-5 shrink-0 text-accent-600" /><span>123 Learning Lane, NY 10001</span></div></div><a href="https://wa.me/15551234567" target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-accent-600 px-5 py-3 font-bold text-text hover:bg-accent-700">Open WhatsApp <ArrowRight className="h-4 w-4" /></a></div><div className="rounded-3xl border border-border bg-surface p-6 shadow-sm sm:p-8">{sent ? <div className="flex min-h-72 flex-col items-center justify-center text-center"><CheckCircle2 className="h-14 w-14 text-primary-600" /><h2 className="mt-5 text-2xl font-black text-text">Message noted!</h2><p className="mt-2 text-text-muted">For the quickest reply, you can also message us on WhatsApp.</p></div> : <form onSubmit={(event) => { event.preventDefault(); setSent(true); }} className="space-y-5"><label className="block"><span className="mb-2 block text-sm font-bold text-text">Your name</span><input required type="text" className="w-full rounded-xl border border-border bg-surface-soft px-4 py-3 text-text outline-none focus:border-primary-400 focus:ring-2 focus:ring-primary-100" /></label><label className="block"><span className="mb-2 block text-sm font-bold text-text">Email address</span><input required type="email" className="w-full rounded-xl border border-border bg-surface-soft px-4 py-3 text-text outline-none focus:border-primary-400 focus:ring-2 focus:ring-primary-100" /></label><label className="block"><span className="mb-2 block text-sm font-bold text-text">How can we help?</span><textarea required rows="5" className="w-full resize-y rounded-xl border border-border bg-surface-soft px-4 py-3 text-text outline-none focus:border-primary-400 focus:ring-2 focus:ring-primary-100" /></label><button type="submit" className="inline-flex items-center gap-2 rounded-xl bg-primary-600 px-5 py-3 font-bold text-white hover:bg-primary-700">Send message <Send className="h-4 w-4" /></button></form>}</div></div></PageShell>;
};

const PolicySection = ({ title, children }) => <section className="border-b border-border py-6 last:border-0"><h2 className="text-xl font-black text-text">{title}</h2><div className="mt-3 space-y-3 leading-relaxed text-text-muted">{children}</div></section>;

export const Privacy = () => <PageShell eyebrow="Your privacy" title="Privacy Policy" intro="Last updated September 3, 2026. This simple policy explains what information A to Z Kids World uses to provide this local shopping experience."><div className="rounded-3xl border border-border bg-surface px-6 sm:px-8"><PolicySection title="Information we use"><p>When you use the demo account, cart, or checkout, information is stored locally in your browser. This may include your email, cart items, theme preference, and delivery details entered for a WhatsApp order.</p></PolicySection><PolicySection title="How we use it"><p>We use this information to keep your account session and cart working, calculate your order, and prepare the message you choose to send through WhatsApp.</p></PolicySection><PolicySection title="Payments and sharing"><p>This website does not process payments or store card details. Your order information is shared with our team only when you choose to open WhatsApp and send the prepared message.</p></PolicySection><PolicySection title="Your choices"><p>You can clear local data through your browser settings, remove items from your cart, or contact us at hello@atozkids.com with privacy questions.</p></PolicySection></div></PageShell>;

export const Terms = () => <PageShell eyebrow="The friendly fine print" title="Terms of Service" intro="By using A to Z Kids World, you agree to use this website responsibly and understand that orders are confirmed directly with our team."><div className="rounded-3xl border border-border bg-surface px-6 sm:px-8"><PolicySection title="Using the site"><p>Use the website to browse products, manage a local cart, and send an order request. Please provide accurate contact and delivery information when contacting our team.</p></PolicySection><PolicySection title="Orders and payment"><p>Adding an item or opening WhatsApp does not guarantee availability or create a completed sale. Our team confirms availability, delivery cost, payment method, and final order details directly with you.</p></PolicySection><PolicySection title="Product information"><p>We aim to keep product descriptions, prices, images, and age guidance accurate. Details may change as our collection grows.</p></PolicySection><PolicySection title="Contact"><p>Questions about an order or these terms can be sent to hello@atozkids.com or through WhatsApp.</p></PolicySection></div></PageShell>;

export const Sitemap = () => <PageShell eyebrow="Find your way" title="Sitemap" intro="Everything currently available in A to Z Kids World."><div className="grid gap-4 sm:grid-cols-2"><Link to="/" className="group rounded-2xl border border-border bg-surface p-5 font-bold text-text transition hover:-translate-y-1 hover:border-primary-300"><span className="text-primary-600">01</span><span className="ml-3">Home</span><ArrowRight className="float-right h-5 w-5 text-text-muted transition group-hover:text-primary-600" /></Link><Link to="/shop" className="group rounded-2xl border border-border bg-surface p-5 font-bold text-text transition hover:-translate-y-1 hover:border-primary-300"><span className="text-primary-600">02</span><span className="ml-3">Shop all toys</span><ArrowRight className="float-right h-5 w-5 text-text-muted transition group-hover:text-primary-600" /></Link><Link to="/about" className="group rounded-2xl border border-border bg-surface p-5 font-bold text-text transition hover:-translate-y-1 hover:border-primary-300"><span className="text-primary-600">03</span><span className="ml-3">About us</span><ArrowRight className="float-right h-5 w-5 text-text-muted transition group-hover:text-primary-600" /></Link><Link to="/contact" className="group rounded-2xl border border-border bg-surface p-5 font-bold text-text transition hover:-translate-y-1 hover:border-primary-300"><span className="text-primary-600">04</span><span className="ml-3">Contact</span><ArrowRight className="float-right h-5 w-5 text-text-muted transition group-hover:text-primary-600" /></Link><Link to="/privacy" className="group rounded-2xl border border-border bg-surface p-5 font-bold text-text transition hover:-translate-y-1 hover:border-primary-300"><span className="text-primary-600">05</span><span className="ml-3">Privacy policy</span><ArrowRight className="float-right h-5 w-5 text-text-muted transition group-hover:text-primary-600" /></Link><Link to="/terms" className="group rounded-2xl border border-border bg-surface p-5 font-bold text-text transition hover:-translate-y-1 hover:border-primary-300"><span className="text-primary-600">06</span><span className="ml-3">Terms of service</span><ArrowRight className="float-right h-5 w-5 text-text-muted transition group-hover:text-primary-600" /></Link></div></PageShell>;
